apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - name: payments
          image: hoantq3008/payments
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: CLIENT_ID
              value: "AU1xc_jrAvb4RbQUmvN2fH8Mh4DcA1LxdKzZa1DoU8MDS-RKtGtkUcbDHLRTFhD-jZfA2NCAK6CJHLB5"
            - name: CLIENT_SECRET
              value: "ELm2IlmPISlSZUuJVUYvPtdlmpLu6WVLyvevW23ma8m7msTZ6lO-fLFN3yjd3lhfR9flmateLlAnu0HW"
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: eztik
            - name: MONGO_URI
              value: "mongodb://payments-mongo-srv:27017/payments"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: payments-srv
spec:
  selector:
    app: payments
  ports:
    - name: payments
      protocol: TCP
      port: 3000
      targetPort: 3000
