name: tests-auth

on: pull_request:
      paths:
        - 'auth/**'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: CI
    env:
      JWT_KEY: ${{secrets.JWT_KEY}}
    steps:
      - uses: actions/checkout@v2
      - run: cd auth && npm install && npm run test:ci
